"""Add is_hidden field to InventoryItem

Revision ID: 247d93a55ae4
Revises: c17644d64225
Create Date: 2025-01-08 08:32:10.463849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247d93a55ae4'
down_revision = 'c17644d64225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    # ### end Alembic commands ###
