"""Add assigned_username column

Revision ID: fdb7af8b1bed
Revises: 9fbb028b1cb6
Create Date: 2025-01-11 17:15:24.867593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb7af8b1bed'
down_revision = '9fbb028b1cb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_username', sa.String(length=80), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])
        batch_op.drop_column('assigned_username')

    # ### end Alembic commands ###
